In [ ]:
import numpy as np 
arr= np.array([])
print(arr)





[]


In [14]:
import numpy as np
import time
n=1000000

# lists
list1=list(range(n))
list2=list(range(n))

start=time.time()
result_list=[list1[i]+list2[i] for i in range(n)]
list_time=time.time()-start

arr1=np.arange(n)
arr2=np.arange(n)

start=time.time()
result_arr=arr1+arr2
numpy_time=time.time()-start

print(f"List Time :{list_time:.6f} sec")
print("Numpy Time :{Numpy_time:.6f}sec")
print(f"Numpy is approximately{list_time/numpy_time:.2f}xfaster")

List Time :103.455998 sec
Numpy Time :{Numpy_time:.6f}sec
Numpy is approximately36.20xfaster


In [15]:
arr=np.array([1,2])
print(arr)

[1 2]


In [17]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [18]:
arr.shape

(2, 3)

In [19]:
arr.ndim

2

In [20]:
arr.size

6

In [21]:
arr.dtype

dtype('int64')

In [26]:
arr = np.zeros((2,3), np.int8)

In [27]:
arr

array([[0, 0, 0],
       [0, 0, 0]], dtype=int8)

In [28]:
arr=np.ones((2,3),np.int8)

In [29]:
arr

array([[1, 1, 1],
       [1, 1, 1]], dtype=int8)

In [31]:
arr=np.empty((2,3),np.int8)

In [32]:
arr

array([[-2, -1, -1],
       [-1,  0,  0]], dtype=int8)

NameError: name 'int8' is not defined

In [ ]:
arr=np.liuspace