In [ ]:

import numpy as np
arr=np.arr([
    [1,2,3],
    [4,5,6]
])
arr.flatten( order r='F')

NameError: name 'arr' is not defined

In [ ]:
arr=np.array([1,2,3,4])
print(arr.dtype)  #datatype
print(arr.ndim)   #dimenation

int64
1


In [5]:
import numpy as np
arr=np.array([[[[1,2,3]]]])
for i in np.nditer(arr):
    print(i)


1
2
3


In [8]:
import numpy as np
arr=np.array([[[[1,2,3]]]])
for i,j in np.ndenumerate(arr):
    print(i,j)


(0, 0, 0, 0) 1
(0, 0, 0, 1) 2
(0, 0, 0, 2) 3


In [9]:
import numpy as np
arr=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9],
    ])
for i,j in np.ndenumerate(arr):
    print(i,j)


(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6
(2, 0) 7
(2, 1) 8
(2, 2) 9


In [14]:
import numpy as np
arr=np.array(
    [1,2,3,4,5,6,7,8])

arr=np.split(arr,4)
arr

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]

In [17]:
import numpy as np
arr=np.array([
    [1,2,3,4],
    [5,6,7,8]]
    )

arr=np.split(arr,2,axis=1)
arr

[array([[1, 2],
        [5, 6]]),
 array([[3, 4],
        [7, 8]])]

In [19]:
import numpy as np
arr=np.array(
    [1,2,3,4,5,6,7,8]
)
arr= np.transpose(arr)
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [20]:
import numpy as np
arr=np.array([
    [1,2,3,4],
    [5,6,7,8]
])
arr= np.transpose(arr)
arr

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [22]:
import numpy as np
arr=np.array(
    [1,2,3,4,9,6]
)
arr=np.sort(arr)
arr

array([1, 2, 3, 4, 6, 9])

In [27]:
arr=np.array([5,3,1,4,2,9])
arr=np.where([arr%2==0])
arr




(array([0, 0]), array([3, 4]))

In [3]:
import numpy as np
arr=np.array([5,3,1,4,2,9])
arr=np.delete(arr,2)
arr

array([5, 3, 4, 2, 9])

In [9]:
import numpy as np
arr=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9],

    ])
# arr=np.delete(arr,1,axis=1)
# arr

arr=np.delete(arr,np.where(arr>5))
arr


array([4, 5, 6, 7, 8, 9])

In [15]:
import numpy as np
arr=np.array([5,3,1,4,2,9])
arr=np.insert(arr,1,99)
arr

arr=np.insert(arr,[2,5],[20,25])
arr

array([ 5, 99, 20,  3,  1,  4, 25,  2,  9])

In [ ]:
import numpy as np
arr=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9],

    ])
# arr=np.insert(arr,2,[1,2,5],axis=1)
# arr

# arr=np.insert(arr,2,99,axis=0)
# arr
arr=np.insert(arr,2,99,axis=1)
arr

array([[ 1,  2, 99,  3],
       [ 4,  5, 99,  6],
       [ 7,  8, 99,  9]])

In [4]:
import numpy as np
arr1=np.array([1,2,3,4,5])
arr2=np.array([2,1,6,7,8])
arr=np.intersect1d(arr1,arr2,assume_unique=True,return_indices=True)
arr

(array([1, 2]), array([0, 1]), array([1, 0]))

In [ ]:
import numpy as np
arr=np.array([
    [1,2,0,3,4,0,5,7],
    [0,12,0,1,2,3,0]])
arr=np.count_nonzero()

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [ ]:
import numpy as np
arr=np.array([
    [1,2,0,3,4,0,5,7],
    [0,12,0,1,2,3,0],])
arr=np.unique().size

In [10]:
import numpy as np

arr = np.array([
    [0, 0, 0, 1, 2, 0, 3, 4, 0, 5, 7],
    [0, 0, 1, 2, 3, 0, 0, 0, 0, 0, 0]
])

result = np.trim_zeros(arr[0], trim='fb')

print(result)

[1 2 0 3 4 0 5 7]


In [12]:
import numpy as np
arr1=np.array([1,2,3,4,5,6])
arr2=np.array([4,5,6,7,8,9])
arr=np.setxor1d(arr,arr2)
arr


array([0, 1, 2, 3, 6, 8, 9])

In [14]:
import numpy as np
arr1=np.array([1,2,3,4,5,6])
arr2=np.array([4,5,6,7,8,9])
arr=np.setdiff1d(arr1,arr2)
arr


array([1, 2, 3])

In [16]:
import numpy as np
arr1=np.array([1,2,3,4,5,6])
arr2=np.array([4,5,6,7,8,9])
arr=np.dot(arr1,arr2)
arr

np.int64(154)

In [19]:
import numpy as np
arr=np.array([
    [1,2,3],
    [4,5,6],
    ])
arr=np.dot(arr,arr.T)
arr

array([[14, 32],
       [32, 77]])

In [24]:
import numpy as np

arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([4,5,6,7,8,9])

arr = np.cross(arr1, arr2)
print(arr)

ValueError: incompatible dimensions for cross product
(dimension must be 2 or 3)

In [14]:
import numpy as np
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([4,5,6,7,8,9])
# arr=np.add(arr1,arr2)
# arr=np.subtract(arr1,arr2)
# arr=np.divide(arr1,arr2)
# arr=np.multiply(arr1,arr2)
# arr=np.power(arr1,arr2)
arr=np.sqrt(arr1)
arr

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974])