In [ ]:
import numpy as np


In [ ]:
#1 create a numpy array 
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
#2 check array properties
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])

print("Array:")
print(arr)

print("Shape:", arr.shape)
print("Size:", arr.size)
print("Data Type:", arr.dtype)
print("Dimensions:", arr.ndim)

Array:
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Size: 6
Data Type: int64
Dimensions: 2


In [ ]:
#3 create a zeros array 
import numpy as np
arr = np.zeros((3,3))

print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
#4 create a ones array 
import numpy as np
arr=np.ones((4,2))
print(arr)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
#5 create a identity matrix
import numpy as np
arr=np.eye(5)
print(arr)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [10]:
#6 create a range array
import numpy as np
arr = np.arange(10, 51, 5)
print(arr)

[10 15 20 25 30 35 40 45 50]


In [11]:
# 7 create evenly spaced values
import numpy as np
arr = np.linspace(0, 100, 11)
print(arr)

[  0.  10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]


In [ ]:
# 8 Reshape an array 
import numpy as np
arr = np.arange(1,13)
arr = arr.reshape(3,4)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
# 9 find the first element
import numpy as np
arr = np.array([10,20,30,40,50])
print(arr[0])

10


In [14]:
# 10 Find the last element 
import numpy as np
arr = np.array([10,20,30,40,50])
print(arr[-1])

50


In [ ]:
#11 Slice an array
import numpy as np
arr = np.arange(1,21)
print(arr[5:11])

[ 6  7  8  9 10 11]


In [ ]:
#12 Find maximum value
import numpy as np
arr = np.array([12,45,67,23,89,34])
print(np.max(arr))

89


In [ ]:
#13 reverse an array 
import numpy as np 
arr= np.array ([1,10])
print(np.rev)

In [ ]:
#14 find minimum value
import numpy as np
arr=np.array([5,6,7,8,3,1,2,3])
print(np.min(arr))


1


In [ ]:
#15 calculate sum 
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
print(np.sum(arr))

150


In [ ]:
#16 calculate mean
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
print(np.mean(arr))


30.0


In [ ]:
#17 find two array 
import numpy as np 
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(arr1 + arr2)

[5 7 9]


In [ ]:
#18 multiply two array
import numpy as np
arr1= np.array ([2,4,5,6])
arr2= np.array([5,6,7,8])
print(arr1*arr2)

[10 24 35 48]


In [ ]:
#19 calculate median
import numpy as np
arr = np.array([5, 10, 15, 20, 25])
print(np.median(arr))

15.0


In [ ]:
#20 find standrd deviation
import numpy as np
arr = np.array([5, 10, 15, 20, 25])
print(np.std(arr))

7.0710678118654755


In [ ]:
#21 square all elements 
import numpy as np
arr = np.array([5, 10, 15, 20, 25])
print(np.square(arr))

[ 25 100 225 400 625]


In [ ]:
#22 find even number
# 
import numpy as np

arr = np.arange(1, 21)
print(arr[arr % 2 == 0])

[ 2  4  6  8 10 12 14 16 18 20]


In [ ]:
#23 count elements greater then 50
# Given [10, 25, 60, 75, 30, 90, 45], count how many elements are greater than 50. 
import numpy as np
arr = np.array([10, 25, 60, 75, 30, 90, 45])
print(np.sum(arr > 50)).size

3


In [ ]:
#24 transpose a matrix 
# Create [[1,2,3],[4,5,6]] and find its transpose.
import numpy as np
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print(arr.T)

[[1 4]
 [2 5]
 [3 6]]


In [ ]:
#25 find row-wise sum
# Given [[1,2,3],[4,5,6],[7,8,9]], find the sum of each row.
import numpy as np
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

print(np.sum(arr, axis=1))


[ 6 15 24]


In [ ]:
# bonus challenge 
# Create a 5×5 matrix containing numbers from 1 to 25.
import numpy as np
arr=np.arange(1,26).reshape(5,5)
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [37]:
# bonus challenge 
# Replace all odd numbers in an array with -1.
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
arr[arr % 2 !=0 ]= -1
print(arr)

[-1  2 -1  4 -1  6 -1  8 -1]


In [38]:
# Bonus Challenge
# Find all numbers divisible by 3 in an array from 1 to 30.
import numpy as np
arr = np.arange(1, 31)
arr = arr[arr % 3 == 0]
print(arr)

[ 3  6  9 12 15 18 21 24 27 30]


In [39]:
# Bonus Challenge
# Create a random array of 10 integers between 1 and 100.
import numpy as np
arr=np.random.randint(1,100,10)
print(arr)

[26 28 40 22 91 14 17 16 44 45]


In [41]:
# Bonus Challenge
# Find the index of the largest element in an array.
import numpy as np
arr=np.array([35,45,6,56,46,76])
index=np.argmax(arr)
print("index of th elements:", index)
print("largest element:", arr[index])

index of th elements: 5
largest element: 76


In [6]:
# create a checkerboard pattern 
# create the following 8*8 matrix 
import numpy as np
arr=np.zeros((8,8), dtype=int) 
arr[1::2, ::2]=1
arr[::2, 1::2]=1
print(arr)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [5]:
import numpy as np
arr=np.ones((8,8), dtype=int) 
for i in range (0,8):
    if i % 2 == 0:
        arr[i, ::2]=0
    else:
        arr[i , 1::2]=0
arr

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [1]:
# border matrix
import numpy as np
arr = np.ones((5,5), dtype=int)
arr[1:4,1:4] = 0
print(arr)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [2]:
# border matrix
import numpy as np
arr = np.zeros((5,5), dtype=int)
arr[1:4,1:4] = 1

print(arr)

[[0 0 0 0 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 0 0 0 0]]


In [7]:
# Replace value
import numpy as np

arr = np.array([5,12,7,18,25,3,15])

arr[arr > 10] = -1

print(arr)

TypeError: 'list' object is not callable

In [8]:
# extract multiples of 3
import numpy as np
arr = np.arange(1,101)
arr = arr[arr % 3 == 0]
print(arr)

[ 3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72
 75 78 81 84 87 90 93 96 99]


In [1]:
# find commaon elements 
import numpy as np

a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8])

result = np.intersect1d(a, b)

print(result)

[4 5]


In [6]:
# find missing number
arr=np.array([1,2,4,6,7,9])
a.max()
a.min()
b=np.arange(1,10)
np.setdiff1d(b,arr)



array([3, 5, 8])

In [7]:
# Row-Wise maximum
import numpy as np
arr = np.array([
    [4,8,2],
    [9,1,5],
    [7,6,3]
])
result = np.max(arr, axis=1)
print(result)

[8 9 7]


In [8]:
import numpy as np

arr = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

result = np.sum(arr, axis=0)

print(result)

[12 15 18]


In [ ]:
# matrix multiplication 
import numpy as np
A = np.array([
    [1,2],
    [3,4]
])
B = np.array([
    [5,6],
    [7,8]
])
result = np.dot(A, B)
print(result)

[[19 22]
 [43 50]]


In [10]:
import numpy as np

arr = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])

print(arr.flatten())

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


In [11]:
import numpy as np

arr = np.arange(24)
print(arr.reshape(2, 3, 4))

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [12]:
import numpy as np

arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

print(arr[:, ::-1])

[[3 2 1]
 [6 5 4]
 [9 8 7]]


In [13]:
import numpy as np

arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

print(arr[::-1, :])

[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [14]:
import numpy as np

arr = np.array([10,5,20,15,8,3])

print(np.sort(arr))

[ 3  5  8 10 15 20]


In [15]:
import numpy as np

arr = np.array([[9,4,7],
                [2,8,1],
                [6,3,5]])

print(np.sort(arr, axis=1))

[[4 7 9]
 [1 2 8]
 [3 5 6]]


In [ ]:
#  find indices of even numbers
