In [4]:
# Create a NumPy array
# Create an array containing numbers from 1 to 10.
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [8]:
# Check array properties
# Create an array and print: Shape, Size, Data type, Number of dimensions.
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr)
print("shape",arr.shape)
print("size",arr.size)
print("datatype",arr.dtype)
print("dimensions",arr.ndim)

[ 1  2  3  4  5  6  7  8  9 10]
shape (10,)
size 10
datatype int64
dimensions 1


In [9]:
# Create a zeros array
# Create a 3×3 array filled with zeros.
arr=np.zeros([3,3])
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [10]:
#  Create a ones array
# Create a 4×2 array filled with ones.
arr=np.ones([4,4])
print(arr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [11]:
# Create an identity matrix
# Create a 5×5 identity matrix.
arr=np.eye(5,5)
print(arr)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [14]:
# 6. Create a range array
# Create an array containing numbers from 10 to 50 with a step of 5.
arr=np.arange(10,51,5)
print(arr)

[10 15 20 25 30 35 40 45 50]


In [15]:
#Create evenly spaced values
# Create 11 evenly spaced numbers between 0 and 100.
arr=np.linspace(1,100,11)
print(arr)

[  1.   10.9  20.8  30.7  40.6  50.5  60.4  70.3  80.2  90.1 100. ]


In [17]:
# Reshape an array
# Create an array from 1 to 12 and reshape it into a 3×4 matrix.
arr=np.arange(1,13)
arr=arr.reshape(3,4)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [18]:
# Find the first element
# Create an array and print its first element.
arr=np.array([1,2,3,4,5,6,6])
print(arr[0])

1


In [19]:
# Find the last element
# Create an array and print its last element.
arr=np.array([2,4,5,6,7,8])
print(arr[-1])

8


In [21]:
# Slice an array
# Create an array from 1 to 20 and print elements from index 5 to index 10.
arr=np.arange(1,21)
print(arr[5:11])

[ 6  7  8  9 10 11]
